### ISSUE TITLE
Works on Darter Pro 5

### ISSUE THREAD

**Issue by necopinus** [stites/system76-nixos#1]
Dropping you a line to let you know that this works on the Darter Pro 5 (`darp5`), or at least it enables backlight control (the only thing I've tested so far/really wanted).

Happy to test other features/capabilities for you on this model if you're interested. I'm pretty familiar with Linux (mostly Arch and Debian), but am a NixOS newbie.

FWIW, I did need to remove all references to the `latest` variable in `system76-nixos/default.nix`, as otherwise `nixos-rebuild` complained. Not sure if this is something weird in my configuration, or something new in 19.09.

**Comment by stites** [comment]
I've given you push access to this repo. I've switched over to a thinkpad as my primary machine and am only intending to use my oryx as a hercules-ci node, so the sys76 kernel packages are no longer at the front of my mind.

RE: `latest`, yes -- that was an issue with the nvidia drivers on my oryx back when I first installed nix -- as I recall this is no longer a problem.

Apologies for not being more helpful, if you'd like to add anything to this repo I can definitely do some code review.

**Comment by necopinus** [comment]
Wow.

Just to clarify where I'm at, I'm currently evaluating/learning NixOS to see how suitable I think it is as part of a larger project, and am doing so by dogfooding the system on my own machine.

If I decide to stick with NixOS, I'll definitely look at adding to/improving the code here. I mostly opened the original ticket to say that this worked on more systems.

Thank you for all the work here so far!

**Comment by mwilsoncoding** [comment]
I'm so glad you created this issue!

I updated the shas and bumped the versions to their latest releases for my attempt.

Works on a `darp6` =]

I may hack away at the other tracked repos as well so I can get backlight and media key control- less vital than the wifi and x11 that I didn't have before cloning this repo :sweat_smile:
